[package]
name = "vislum-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
atomicow = { workspace = true }
crossbeam = { workspace = true }
notify-debouncer-full = "0.5.0"