[package]
name = "vislum-rhi"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { workspace = true }
log = { workspace = true }
vislum-rhi-macros = { path = "./macros" }
gpu-allocator = { version = "0.28.0", features = ["vulkan"] }
thiserror = { workspace = true }